name: ForSyDe-Atom
description: A Layered Framework for Modeling Cyber-Physical Systems
remote_theme: forsyde/forsyde-web-theme

parent-url: https://forsyde.github.io

maintainer:
  name: ugeorge
  url: https://github.com/ugeorge

github-releases:
  zip_url: https://api.github.com/repos/forsyde/forsyde-atom/zipball/master
  tar_url: https://api.github.com/repos/forsyde/forsyde-atom/tarball/master

## paths to exclude from the site generation
exclude: [Gemfile, Gemfile.lock, README.md, LICENSE, Setup.hs, setup.html, src, tests, '*cabal*', dist, fig]

## Useful links
shortcuts:
 - name: User Manual
   url: https://forsyde.github.io/forsyde-atom/assets/manual.pdf
 - name: API Documentation
   url: https://forsyde.github.io/forsyde-atom/api/
 - name: Examples
   url: https://github.com/forsyde/forsyde-atom-examples

plugins:
- jekyll-seo-tag
- jekyll-remote-theme
- jekyll-sitemap