#!/bin/bash


# sed -i 's/<link href="ocean.css"[^>]*>//g' *.html
# sed -i 's/<link [^>]*>//g' *.html
# sed -i 's|<script [^>]*></script>||g' *.html

# for f in *.html; do
#     echo -e "---
# layout: haddock
# ---
# $(cat $f)" > $f
# done


sed -i 's|<!DOCTYPE html.*</head>||g' *.html
# perl -pi -e 's{ \b <!DOCTYPE html \b .*? \b </head> \b}{}x' *.html
sed -i 's|<body>||g' *.html
sed -i 's|</body>||g' *.html
